### ISSUE TITLE
meetingManager.join throws error when microphone & camera permission is denied 

### ISSUE THREAD

**Issue by junedlanja** [aws/amazon-chime-sdk-component-library-react#350]
**Describe the bug**
If permission is denied for microphone and camera. meetingManager.join is throwing error.

**To Reproduce**
1. Block microphone and camera
2. join the meeting

**Expected behavior**
It should join the meeting but getting this error. 

**Screenshots**
![Screenshot 2021-01-05 at 1 34 21 AM](https://user-images.githubusercontent.com/11869570/103574756-837f2000-4ef6-11eb-8461-c3060c55f673.png)

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : chrome
 - Version : chrome 87.0.4280.88  and ios 10.14.6

**Comment by RidipDe** [comment]
Can you please confirm the SDK version in use?

**Comment by junedlanja** [comment]
```
"amazon-chime-sdk-component-library-react": "^1.6.0",
"amazon-chime-sdk-js": "^2.3.0",
```

**Comment by ltrung** [comment]
@junedlanja this seems to be a similar to issue #365. We are working on a fix for the issue. In the mean time, can you use amazon-chime-sdk-js version 1.22.

**Comment by anuranduttaroy** [comment]
@junedlanja could you try out the latest changes from master branch and see if that fixes your issue?

**Comment by vidya-mohan** [comment]
Resolving as this is similar to #365 which has been resolved

**Comment by OriginLive** [comment]
Hi, this issue is still present on latest chime library
![image](https://user-images.githubusercontent.com/24319526/112640269-76ad0100-8e41-11eb-9d17-d8e74ebd039b.png)
